### ISSUE TITLE
[device] websocket token returns mimetype and or wrong encoding

### ISSUE THREAD

**Issue by jonau** [Cross-Lab-Project/crosslab#12]
Python clients responds with `message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('http://localhost/devices/ef416742-5c7c-42e4-8176-df8a7bf051eb/websocket')`

According to the API the response should be:
```
    200:
      description: The newly generated websocket token for the device.
      content:
        application/json:
          schema:
            type: string
```
